#!/usr/bin/env node
/* ============================================================
   LeadaLine Demo Factory — self-contained UI builder.
   Reads factory/index.src.html and inlines every local <script src>
   (the engine, profiles, research, zip and app) into a SINGLE file
   factory/index.html.

   Why: a single self-contained file works however it's opened —
   file://, GitHub Pages, downloaded on its own, emailed, or served
   under a strict CSP. No sibling scripts to fail to load, so the
   Generate button always works.

   Usage:  node scripts/build-factory.cjs
   ============================================================ */
'use strict';
var fs = require('fs');
var path = require('path');

var ROOT = path.resolve(__dirname, '..');
var FACTORY = path.join(ROOT, 'factory');
var SRC = path.join(FACTORY, 'index.src.html');
var OUT = path.join(FACTORY, 'index.html');

var html = fs.readFileSync(SRC, 'utf8');

// Match: <script src="local/path.js"></script>  (ignores http(s):// and //)
var re = /([ \t]*)<script\s+src=["'](?!https?:|\/\/)([^"']+)["']\s*>\s*<\/script>/gi;
var inlined = 0;

html = html.replace(re, function (m, indent, rel) {
  var file = path.join(FACTORY, rel);
  if (!fs.existsSync(file)) {
    console.warn('  ! skipped (not found): ' + rel);
    return m;
  }
  var code = fs.readFileSync(file, 'utf8');
  // Defensive: never let an embedded closing tag break out of the <script>.
  code = code.replace(/<\/script/gi, '<\\/script');
  inlined++;
  return indent + '<script data-inlined="' + rel + '">\n' + code + '\n' + indent + '</script>';
});

var banner = '<!-- ============================================================\n' +
  '     LeadaLine Demo Factory — SELF-CONTAINED build.\n' +
  '     Generated from factory/index.src.html by scripts/build-factory.cjs.\n' +
  '     Do not edit this file directly — edit index.src.html or the modules\n' +
  '     in factory/ and factory/engine/, then re-run the build.\n' +
  '     ============================================================ -->\n';
html = html.replace(/^<!DOCTYPE html>/i, '<!DOCTYPE html>\n' + banner);

fs.writeFileSync(OUT, html);
console.log('Built factory/index.html (self-contained) — ' + inlined + ' script(s) inlined, ' + html.length + ' bytes.');
